name: publish-ts-proto-buf-remote-plugin

on:
  workflow_dispatch:
    inputs:
      ts_proto_version:
        description: 'Version of ts-proto. e.g. 1.110.4'
        type: string
        required: true
      buf_registry_patch_version:
        description: 'Buf registry patch version'
        type: number
        required: false
        default: 0

env:
  BUF_USER: kanziw
  BUF_TOKEN: ${{ secrets.BUF_TOKEN }}

jobs:
  publish-ts-proto-buf-remote-plugin:
    name: "[v${{ github.event.inputs.ts_proto_version }}] Publish ts-proto buf remote plugin with version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Buf Registry
        uses: docker/login-action@v1 
        with:
          registry: plugins.buf.build
          username: ${{ env.BUF_USER }}
          password: ${{ secrets.BUF_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.tsproto
          push: true
          tags: plugins.buf.build/${{ env.BUF_USER }}/ts-proto:v${{ github.event.inputs.ts_proto_version }}-${{ github.event.inputs.buf_registry_patch_version }}
          build-args: TS_PROTO_VERSION=${{ github.event.inputs.ts_proto_version }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
